config/routes.rb
Rails.application.routes.draw do

  root 'athletes#new'

  resources :athletes do
    member do
        get :fans, :follows
    end
    resources :stats, shallow: true
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get '/signup',  to: 'athletes#new',  as: 'signup'
  get '/login', to: 'sessions#create', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout

  get 'welcome', to: 'athletes#new', as: 'welcome'


end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  before_save :set_email_to_lowercase
  before_create :create_remember_token

  validates :first_name, :last_name, :email, presence: true
  validates_uniqueness_of :email

  has_many :stats,  dependent: :destroy

  belongs_to :high_school
  belongs_to :sport
  belongs_to :position

  accepts_nested_attributes_for :high_school
  accepts_nested_attributes_for :sport
  accepts_nested_attributes_for :position

  has_attached_file :avatar, :styles => { :medium => "350X350>", :thumb => "100X100>" }, default_url: '/images/normal/missing.png'
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_secure_password

  def athlete_last_stat
    if stats.empty?
      "No stats yet!"
    else
      stats.last
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def Athlete.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Athlete.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def set_email_to_lowercase
    self.email = email.downcase
  end

  def create_remember_token
    self.remember_token = Athlete.digest(Athlete.new_remember_token)
  end

end

app/models/high_school.rb
class HighSchool < ActiveRecord::Base
  has_many :athletes

  accepts_nested_attributes_for :athletes
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :athletes
  belongs_to :sport
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :fan, class_name: "Athlete"
  belongs_to :followed, class_name: "Athlete"
  validates :fan_id, presence: true
  validates :follow_id, presence: true
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :athletes
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  belongs_to :athlete
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController

  def index
    @athletes = Athlete.all
  end

  def show
    @athlete = Athlete.find(params[:id])
  end

  def new
    @athlete = Athlete.new
  end

  def edit
    @athlete = Athlete.find(params[:id])
  end

  def create
    @athlete = Athlete.new(athlete_params)
    @athlete.high_school ||= HighSchool.last #assign a default high school
    if @athlete.save
      sign_in @athlete
      flash[:success] = "You were successfully created."
      redirect_to edit_athlete_url(@athlete)
    else
      render :new
    end
  end

  def update
    @athlete = Athlete.find(params[:id])
    if @athlete.update_attributes(athlete_params)
      flash[:success] = "Profile Updated!"
      redirect_to @athlete
    else
      render 'edit'
    end
  end

  def destroy
    Athlete.find(params[:id]).destroy
    flash[:success] = "Athlete deleted."
    redirect_to athlete_url
  end

  private

    def athlete_params
      params.require(:athlete).permit!
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    athlete = Athlete.find_by_email(params[:email])
    if athlete && athlete.authenticate(params[:password])
      sign_in athlete
      redirect_to athletes_path
    else
      flash[:error] = 'Invalid email/password combination'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def index
    @stats = current_athlete.stats.order(created_at: :desc)
  end

  def show
  end

  def new
    @stat = Stat.new
  end

  def edit
  end

  def create
    @stat = current_athlete.stats.build(stat_params)
    if @stat.save
      redirect_to athlete_stats_url, flash: { success: 'Stat saved!' }
    else
      render :new
    end
  end

  def update
  end

  def destroy
    @stat = Stat.find(params[:id])
    @stat.destroy

    redirect_to athletes_url
  end

  private

    def stat_params
      params.require(:stat).permit(:points, :rebounds, :assists, :blocks,
                                   :turnovers, :minutes_played, :date_played,
                                   :athlete_id)
    end

    def correct_athlete
      @stat = current_athlete.stats.find_by(id: params[:id])
      redirect_to athletes_path if @stat.nil?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
  def full_name athlete
   return "" unless athlete
   "#{athlete.first_name} #{athlete.last_name}"
  end

  def welcome_name athlete
    return "" unless athlete
    "#{athlete.first_name} #{athlete.last_name[0]}"
  end

  def athlete_high_school athlete
    "#{athlete.high_school_name}"
  end

  def setup_hs athlete
    athlete.high_school ||= HighSchool.new
    athlete
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(athlete)
    remember_token = Athlete.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    athlete.update_attribute(:remember_token, Athlete.digest(remember_token))
    self.current_athlete = athlete
  end

  def sign_out
    current_athlete.update_attribute(:remember_token,
                                  Athlete.digest(Athlete.new_remember_token))
    cookies.delete(:remember_token)
    self.current_athlete = nil
  end

  def current_athlete=(athlete)
    @current_athlete = athlete
  end

  def current_athlete
    remember_token = Athlete.digest(cookies[:remember_token])
    @current_athlete ||= Athlete.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_athlete.nil?
  end

  def athlete_signed_in?
    current_athlete.present?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to login_path, notice: "Please log in."
    end
  end

end

app/views/athletes/_edit_form.html.slim
.signup-form
  = simple_form_for(@athlete) do |f|
    - if @athlete.errors.any?
      #error_explanation
        h2
          = pluralize(@athlete.errors.count, "error ")
          | prohibited you from being saved:
        ul
          - @athlete.errors.full_messages.each do |message|
            li= message
    .image
      = image_tag @athlete.avatar.url(:medium), :id => "preview"
      = f.file_field :avatar
    .confirm
      = f.input :first_name, label: false
      = f.input :last_name, label: false
      = f.input :email, label: false
      = f.input :grad_year, label: false
      = f.input :height, label: false
      = f.input :weight, label: false
      = f.association :high_school, value_method: :id
      = f.association :sport, value_method: :id
      = f.association :position, value_method: :id
    .submit
      = f.button :submit, value: "Update Profile"

app/views/athletes/_edit_profile.html.slim
= simple_form_for(@athlete) do |f|
  - if @athlete.errors.any?
    #error_explanation
      h2
        = pluralize(@athlete.errors.count, "error ")
        | prohibited you from being saved:
      ul
        - @athlete.errors.full_messages.each do |message|
          li= message
  .edit_profile_form
    .split_form
      .image.mal
        = image_tag @athlete.avatar.url(:medium), :id => "preview"
        = f.file_field :avatar
    .split_form.row
      = f.input :grad_year, input_html: { class: 'basic-slide' }
      = f.input :height, input_html: { class: 'basic-slide' }
      = f.input :weight, input_html: { class: 'basic-slide' }
      = f.simple_fields_for :high_school do |hs|
        = hs.input :name, collection: HighSchool.all.order(:name), input_html: { class: 'basic-select' }
      = f.association :sport, value_method: :id, input_html: { class: 'basic-select' }
      = f.association :position, value_method: :id, input_html: { class: 'basic-select' }
  .submit
    = f.button :submit, value: "Update Profile"

app/views/athletes/_form.html.slim
.form
  = simple_form_for(@athlete) do |f|
    - if @athlete.errors.any?
      #error_explanation
        h2
          = pluralize(@athlete.errors.count, "error")
          | prohibited this user from being saved:
        ul
          - @athlete.errors.full_messages.each do |message|
            li= message

    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
    = f.button :submit

app/views/athletes/_signup_form.html.slim
.signup-form
  = simple_form_for(@athlete) do |f|
    - if @athlete.errors.any?
      #error_explanation
        h2
          = pluralize(@athlete.errors.count, "error ")
          | prohibited you from being saved:
        ul
          - @athlete.errors.full_messages.each do |message|
            li= message
    .name
      = f.input :first_name, label: false, input_html: { class: 'first-name' }, error_html: { class: 'error'}
      = f.input :last_name, label: false, input_html: { class: 'last-name' }, error_html: { class: 'error'}
    .confirm
      = f.input :email, label: false, error_html: { class: 'error'}
      = f.input :password, label: false, error_html: { class: 'error'}
      = f.input :password_confirmation, label: false, error_html: { class: 'error'}
    .submit
      = f.button :submit, value: "Create"

app/views/athletes/edit.html.slim
.form-container.quarter
  .section
    h1.title= "#{full_name(current_athlete)}"
    = render 'edit_profile'

app/views/athletes/index.html.slim
.feed
  - @athletes.each do |athlete|
    =link_to athlete_path(athlete)
      .card
        .card_image
          - if athlete.avatar?
            = image_tag athlete.avatar.url(:medium)
          - else
            i.fa.fa-picture-o
            p.picture-content Profile Picture Not Set Yet
          .card_player
            p.large-font.strong= athlete.full_name
            / p= athlete.high_school.name
        .card_stat
          p= "#{athlete.athlete_last_stat}"
        .card_player_profile
          .profile_column_1
            / p= athlete.sport.name
            / p= athlete.position.name
          .profile_column_2
            p= athlete.height
            p= athlete.weight

app/views/athletes/new.html.slim
.welcome-page
  .content
    h1.content-header
      | Level the playing field.
    = render 'signup_form'
    h4.content-sub-header
      | Showcase your stats, highlights and general awesomeness to prospective Coaches, fellow Athletes and avid Fans

app/views/athletes/show.html.slim
.container
  .section
    .card
      .card_image
        - if @athlete.avatar?
          = image_tag @athlete.avatar.url(:medium)
          = @athlete.full_name
          p= @athlete.high_school
        - else
          i.fa.fa-picture-o
          p.picture-content Profile Picture Not Set Yet
          .card_player
            p= @athlete.full_name
            p= @athlete.high_school

        a= link_to "Follow"

app/views/layouts/_footer.html.slim
.footer
  nav.nav
    ul.footer-list
      li.footer-list--item 2014 The College Roster
      li.footer-list--item Privacy Policy
      li.footer-list--item Contact Us

app/views/layouts/_header.html.slim
#header.header
  - if athlete_signed_in?
    .header-logo
      a= link_to athletes_path
        = image_tag "tcr_white.png"
  - else
    .header-logo
      a= link_to root_path
        p The College Roster
  - if athlete_signed_in?
    ul.header-nav
      li
        a= link_to edit_athlete_path(current_athlete)
          i.fa.fa-dribbble
          | Profile
      li
        a= link_to new_athlete_stat_path(current_athlete)
          i.fa.fa-signal
          | Stats
      li
        a= link_to athletes_path
          i.fa.fa-users
          | Athletes
    .header-signin
      p= "Hi, #{welcome_name current_athlete}"
      a= link_to "Sign Out", logout_path
  - else
    .welcome-signin
      a= link_to "Sign In", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title TheCollegeRoster
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    link href="http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic" rel="stylesheet" type="text/css" /
    link href='http://fonts.googleapis.com/css?family=Droid+Sans:700' rel='stylesheet' type='text/css'
    link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css" rel="stylesheet" /
  body
    =render 'layouts/header'
    .page
      = yield
      = debug(params) if Rails.env.development?

app/views/shared/_create_stat.html.slim
.left-nav
  ul
    li.left-nav-item
      a= link_to new_athlete_stat_path(current_athlete)
        i.fa.fa-plus
    li.left-nav-item
      a= link_to athlete_stats_path(current_athlete)
        i.fa.fa-university

.athlete-stats
  .container-half.stat-create
    h1.stat-header Log Your Last Stat
    .stat-form
      =simple_form_for :stat, url: athlete_stats_path do |f|
        .inputs
          =f.input :date_played, as: :date, wrapper_html: { class: 'stat-date' }
          =f.input :points, wrapper_html: { class: 'stat-input' }
          =f.input :rebounds, wrapper_html: { class: 'stat-input' }
          =f.input :assists, wrapper_html: { class: 'stat-input' }
          =f.input :blocks, wrapper_html: { class: 'stat-input' }
          =f.input :turnovers, wrapper_html: { class: 'stat-input' }
          =f.input :minutes_played, wrapper_html: { class: 'stat-input' }
          =f.button :submit, class: 'stat-submit'

app/views/shared/_recent_stat.html.slim
/ - @stats.each do |stat|
  / p= stat.points

p

app/views/stats/_athlete_stat_feed.html.slim
table.stat-table
  thead
    th Date Played
    th Points
    th Rebounds
    th Assists
    th Turnovers
    th Blocks
    th Steals
    th Minutes Played
  tbody
    - @stats.each do |stat|
      tr
        td= stat.date_played
        td= stat.points
        td= stat.rebounds
        td= stat.assists
        td= stat.turnovers
        td= stat.blocks
        td= stat.steals
        td= stat.minutes_played

app/views/stats/index.html.slim
.left-nav
  ul
    li.left-nav-item
      a= link_to new_athlete_stat_path(current_athlete)
        i.fa.fa-plus
    li.left-nav-item
      a= link_to athlete_stats_path(current_athlete)
        i.fa.fa-university

.container
  table.stats-table
    thead
      th Date Played
      th Points
      th Rebounds
      th Assists
      th Steals
      th Blocks
      th Turnovers
      th Minutes
    - @stats.each do |stat|
      tbody
        td= stat.date_played
        td= stat.points
        td= stat.rebounds
        td= stat.assists
        td= stat.steals
        td= stat.blocks
        td= stat.turnovers
        td= stat.minutes_played

app/views/stats/new.html.slim
.left-nav
  ul
    li.left-nav-item
      a= link_to new_athlete_stat_path(current_athlete)
        i.fa.fa-plus
    li.left-nav-item
      a= link_to athlete_stats_path(current_athlete)
        i.fa.fa-university

.athlete-stats
  .container-half.stat-create
    h1.stat-header Log Your Last Stat
    .stat-form
      =simple_form_for :stat, url: athlete_stats_path do |f|
        .inputs
          =f.input :date_played, as: :date, wrapper_html: { class: 'stat-date' }
          =f.input :points, wrapper_html: { class: 'stat-input' }
          =f.input :rebounds, wrapper_html: { class: 'stat-input' }
          =f.input :assists, wrapper_html: { class: 'stat-input' }
          =f.input :steals, wrapper_html: { class: 'stat-input' }
          =f.input :blocks, wrapper_html: { class: 'stat-input' }
          =f.input :turnovers, wrapper_html: { class: 'stat-input' }
          =f.input :minutes_played, wrapper_html: { class: 'stat-input' }
          =f.button :submit, class: 'stat-submit'